name: Build WPF Project

on:
  pull_request:
    branches:
      -main

jobs:
  build:
    run_on:
      windows_latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 4.8.x

          - name: Install NuGet
      run: choco install nuget.commandline

    - name: Restore NuGet packages
      run: nuget restore

    - name: Build solution
      run: msbuild /p:Configuration=Release

    - name: Publish build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: '**/bin/Release/**'
