name: Build WPF Project

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
    

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install NuGet
      run: choco install nuget.commandline

    - name: Restore NuGet packages
      run: nuget restore

    - name: Build solution
      run: msbuild /p:Configuration=Release

    - name: Publish build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: '**/bin/Release/**'
